Ext.define('mis.store.Articles',{
    extend:'Ext.data.Store',
    model:'gwtjs.model.Article',
    pageSize:18,
    proxy:{
        type:'ajax',
        api:{
            read:basePath+'/action/article/getArticles.action',
            create:basePath+'/action/article/editor.action',
            update:basePath+'/action/article/editor.action',
            destroy:basePath+'/action/article/deletes.action'
        },
        reader:{
            type:'json',
            successProperty:'flag',
            root:'pager.entityList',
            totalProperty: 'pager.totalCounts',
            messageProperty:'message'
        },
        writer:{
            type:'json'
        }
    }
})